package com.vankong.forward.bankcardsyn;

import java.io.Serializable;;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table "BANK_CARD_BEAN".
 */
public class BankCardBean implements Serializable {

    private String id;
    private String cardNO;
    private String clientID;
    private String bankCodeNum;
    private Boolean isUse;
    private String bankCardPurpose;
    private String editflag;
    private String syncFailResaon;
    private String holderType;
    private String holderName;
    private String idType;
    private String idCardType;
    private String countryID;
    private String city;
    private String privince;
    private String idCardNO;
    /**
     * 银行卡状态描述
     */
    private String CardStatusDesc;
    /**
     * 银行卡状态码值
     */
    private Integer CardStatus;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public BankCardBean() {
    }

    public BankCardBean(String id) {
        this.id = id;
    }

    public BankCardBean(String id, String cardNO, String clientID, String bankCodeNum, Boolean isUse, String bankCardPurpose, String editflag, String syncFailResaon, String holderType, String holderName, String idType, String idCardType, String countryID, String city, String privince, String idCardNO, String CardStatusDesc, Integer CardStatus) {
        this.id = id;
        this.cardNO = cardNO;
        this.clientID = clientID;
        this.bankCodeNum = bankCodeNum;
        this.isUse = isUse;
        this.bankCardPurpose = bankCardPurpose;
        this.editflag = editflag;
        this.syncFailResaon = syncFailResaon;
        this.holderType = holderType;
        this.holderName = holderName;
        this.idType = idType;
        this.idCardType = idCardType;
        this.countryID = countryID;
        this.city = city;
        this.privince = privince;
        this.idCardNO = idCardNO;
        this.CardStatusDesc = CardStatusDesc;
        this.CardStatus = CardStatus;
    }

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getCardNO() {
        return cardNO;
    }

    public void setCardNO(String cardNO) {
        this.cardNO = cardNO;
    }

    public String getClientID() {
        return clientID;
    }

    public void setClientID(String clientID) {
        this.clientID = clientID;
    }

    public String getBankCodeNum() {
        return bankCodeNum;
    }

    public void setBankCodeNum(String bankCodeNum) {
        this.bankCodeNum = bankCodeNum;
    }

    public Boolean getIsUse() {
        return isUse;
    }

    public void setIsUse(Boolean isUse) {
        this.isUse = isUse;
    }

    public String getBankCardPurpose() {
        return bankCardPurpose;
    }

    public void setBankCardPurpose(String bankCardPurpose) {
        this.bankCardPurpose = bankCardPurpose;
    }

    public String getEditflag() {
        return editflag;
    }

    public void setEditflag(String editflag) {
        this.editflag = editflag;
    }

    public String getSyncFailResaon() {
        return syncFailResaon;
    }

    public void setSyncFailResaon(String syncFailResaon) {
        this.syncFailResaon = syncFailResaon;
    }

    public String getHolderType() {
        return holderType;
    }

    public void setHolderType(String holderType) {
        this.holderType = holderType;
    }

    public String getHolderName() {
        return holderName;
    }

    public void setHolderName(String holderName) {
        this.holderName = holderName;
    }

    public String getIdType() {
        return idType;
    }

    public void setIdType(String idType) {
        this.idType = idType;
    }

    public String getIdCardType() {
        return idCardType;
    }

    public void setIdCardType(String idCardType) {
        this.idCardType = idCardType;
    }

    public String getCountryID() {
        return countryID;
    }

    public void setCountryID(String countryID) {
        this.countryID = countryID;
    }

    public String getCity() {
        return city;
    }

    public void setCity(String city) {
        this.city = city;
    }

    public String getPrivince() {
        return privince;
    }

    public void setPrivince(String privince) {
        this.privince = privince;
    }

    public String getIdCardNO() {
        return idCardNO;
    }

    public void setIdCardNO(String idCardNO) {
        this.idCardNO = idCardNO;
    }

    public String getCardStatusDesc() {
        return CardStatusDesc;
    }

    public void setCardStatusDesc(String CardStatusDesc) {
        this.CardStatusDesc = CardStatusDesc;
    }

    public Integer getCardStatus() {
        return CardStatus;
    }

    public void setCardStatus(Integer CardStatus) {
        this.CardStatus = CardStatus;
    }

    // KEEP METHODS - put your custom methods here

    @Override
    public String toString() {
        return "BankCardBean{" +
                "cardNO='" + cardNO + '\'' +
                ", clientID='" + clientID + '\'' +
                ", bankCodeNum='" + bankCodeNum + '\'' +
                ", isUse=" + isUse +
                ", bankCardPurpose='" + bankCardPurpose + '\'' +
                ", editflag='" + editflag + '\'' +
                ", syncFailResaon='" + syncFailResaon + '\'' +
                ", holderType='" + holderType + '\'' +
                ", holderName='" + holderName + '\'' +
                ", idType='" + idType + '\'' +
                ", idCardType='" + idCardType + '\'' +
                ", countryID='" + countryID + '\'' +
                ", city='" + city + '\'' +
                ", privince='" + privince + '\'' +
                ", idCardNO='" + idCardNO + '\'' +
                '}';
    }
    // KEEP METHODS END

}
